# =============================================================================
# Generated by amplifier-bundle-dev-machine — do not edit directly
# Amplifier Dev-Machine Container: ridecast2
#
# Sandboxed environment for autonomous AI agent execution.
# Agents have bash access but can only affect the bind-mounted project directory.
#
# Build:  docker compose -f docker-compose.dev-machine.yaml build
# Run:    docker compose -f docker-compose.dev-machine.yaml up -d
# Shell:  docker compose -f docker-compose.dev-machine.yaml exec dev-machine bash
#
# ---- Template variables ------------------------------------------------------
#
#   node:22.14-bookworm-slim           — Docker base image
#                              Python-primary: python:3.12-slim
#                              Node-primary:   node:22-bookworm-slim
#
#   501             — Host user UID (bind-mount permission compatibility)
#   20             — Host user GID (bind-mount permission compatibility)
#   chrispark             — Host username; must equal $(basename /Users/chrispark)
#   /Users/chrispark            — Absolute home path matching the HOST user's $HOME
#                              e.g. /home/youruser
#                              MUST match host path — bind-mounts use this path
#
#   ridecast2         — Short project identifier, e.g. word4
#   /Users/chrispark/Projects/ridecast2          — Absolute path to project root
#                              e.g. /home/youruser/dev/my-project
#
#   0.10.4           — Pinned uv version, e.g. 0.10.4
#                              Never use :latest — version skew breaks lockfiles
#
#    python3 python3-pip python3-venv      — Extra apt packages, space-separated (may be empty)
#                              Node base images need: python3 python3-pip python3-venv
#                              build-essential + python3-dev are included by default
#                              for native module compilation (better-sqlite3, sharp, etc.)
#
#              — Multi-line Node.js setup block, or empty string
#                              For Python-primary projects that need Node (e.g. pyright):
#                                RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
#                                    && apt-get install -y --no-install-recommends nodejs \
#                                    && rm -rf /var/lib/apt/lists/*
#                              For Node base images or projects that don't need Node: leave empty
#
#        — uv tool install lines for Python dev tools, or empty
#                              Example: RUN uv tool install ruff && uv tool install pyright
#                              Leave empty for Node-primary projects without Python analysis
#
#      — Additional system-python pip packages beyond pyyaml (may be empty)
#
#   npm ci      — Project dependency install command, e.g.:
#                                pnpm install --frozen-lockfile
#                                uv sync --extra dev
#                              NOT used here — project source is bind-mounted at runtime,
#                              not available during docker build. Used in entrypoint.sh.
# =============================================================================

# VERSION PINNING GUIDANCE:
# ALWAYS pin node:22.14-bookworm-slim to a specific digest or version tag -- NEVER use :latest.
#   Good:  python:3.12.9-slim   node:22.14-bookworm-slim
#   Bad:   python:latest        node:22-bookworm-slim  (minor version can drift)
# Rationale: reproducible builds -- a fresh docker build months later should produce
# the same environment. Unpinned base images silently break when the upstream tag moves.
# Update base image intentionally; commit the change with a reason in the commit message.
#
# LOCK FILE DISCIPLINE:
# Project dependencies MUST be installed from a lock file:
#   Python:    uv sync (reads uv.lock) -- never `pip install` without pinning
#   Node.js:   pnpm install --frozen-lockfile  or  npm ci
#   Rust:      cargo build (Cargo.lock is committed)
# The entrypoint.sh installs project dependencies (npm ci for reproducible installs).
# If no lock file exists: create one before deploying the machine (run the install once
# on the host, commit the lock file, then use the frozen/locked variant in the container).

FROM node:22.14-bookworm-slim

# -- System dependencies -------------------------------------------------------
# git            — commits, branch ops, safe.directory config
# curl           — API pre-flight check in entrypoint; nodesource / apt key scripts
# ca-certificates — HTTPS for git+https Amplifier install and LLM API calls
# jq             — used in recipe bash steps for JSON parsing
#  python3 python3-pip python3-venv — project-specific extras; placed inline to avoid an
#                       orphaned backslash when the variable is empty
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        python3-dev \
        openssh-client \
        git \
        curl \
        ca-certificates \
        jq  python3 python3-pip python3-venv \
    && rm -rf /var/lib/apt/lists/*

# -- Node.js setup (optional) --------------------------------------------------
# Python-primary projects that need Node.js (e.g. for the pyright LSP server):
#   set  to the nodesource install block shown in the header above.
# Node-primary projects (node:*-* base images): Node is already present,
#   leave  empty — this section becomes a harmless blank line.


# -- System Python: pyyaml + extras --------------------------------------------
# Recipe bash steps call `python3 -c "import yaml; ..."` to read/write STATE.yaml.
# pyyaml MUST live in system python3 — outside any project venv — so it is
# available unconditionally in every bash step, even before `uv sync` runs.
#
# --break-system-packages: required on Debian/Ubuntu base images (PEP 668
# "externally managed environment"). Harmless on official python:* images.
#
# Node base images: ensure python3-pip is included in  python3 python3-pip python3-venv.
#  may be empty — trailing space on the install line is fine.
RUN python3 -m pip install --no-cache-dir --break-system-packages \
        pyyaml 

# -- uv (pinned version) -------------------------------------------------------
# Copied directly from the official uv image — no curl|bash, no apt package.
# Pinned to 0.10.4 to match the host and keep uv.lock compatible.
# Update intentionally when you want to upgrade; never set :latest.
COPY --from=ghcr.io/astral-sh/uv:0.10.4 /uv /uvx /usr/local/bin/

# -- Non-root user (UID/GID must match host for bind-mount permissions) --------
# Running as root causes permission issues: files written to the bind-mounted
# project directory become root-owned, blocking host-side cron monitors,
# `git status`, and any tooling that runs as the unprivileged host user.
#
# /Users/chrispark MUST equal the host user's $HOME (e.g. /home/youruser) so
# that bind-mounted paths (project dir, .ssh/known_hosts) resolve identically
# inside the container.  chrispark must equal $(basename /Users/chrispark).
ARG USER_UID=501
ARG USER_GID=20

# Idempotent: -f skips if group/user already exists (e.g. node base images
# that ship UID 1000 as 'node').  The || true handles both the -f flag
# (which isn't universal across addgroup/adduser implementations) and the
# case where the UID is already claimed under a different name.
RUN groupadd -f -g ${USER_GID} chrispark 2>/dev/null || true \
    && id -u chrispark >/dev/null 2>&1 \
    || useradd -m -u ${USER_UID} -g ${USER_GID} -s /bin/bash \
         -d /Users/chrispark chrispark

# -- Install Amplifier as the non-root user ------------------------------------
# Installing as root leaves shebangs pointing at /root/.local/... which breaks
# after the USER switch.  We install as chrispark so uv puts binaries in
# /Users/chrispark/.local/bin/ with correct shebangs.
USER chrispark
ENV PATH="/Users/chrispark/.local/bin:${PATH}"

RUN uv tool install amplifier --from "git+https://github.com/microsoft/amplifier"

# -- Python dev tools (optional) -----------------------------------------------
# ruff, pyright, pytest, etc.  Leave  empty to skip.


# -- Git identity for container commits ----------------------------------------
# safe.directory allows git to operate on the bind-mounted project dir
# (owned by host UID, which matches container UID).
#
# URL rewrite: pushInsteadOf rewrites HTTPS → SSH for PUSH operations only.
# Clone/fetch stays HTTPS — this works for public repos without credentials
# and for private repos when a credential helper (e.g. gh auth) is configured.
# Push uses the forwarded SSH agent.
#
# Previous design used insteadOf (rewrites ALL operations), which forced every
# clone through SSH and broke when SSH agent forwarding was unreliable. The
# pushInsteadOf approach is more resilient: clone/fetch work even without SSH,
# and in branching_mode=false the container never pushes (host handles pushes).
#
# If the host has `gh` CLI, its credential helper is configured below to
# provide HTTPS auth for private repo clones. See RUN git config --global credential.helper "!gh auth git-credential".
RUN git config --global user.name "ridecast2 Dev Machine" && \
    git config --global user.email "dev-machine@ridecast2.local" && \
    git config --global --add safe.directory /Users/chrispark/Projects/ridecast2 && \
    git config --global url."git@github.com:".pushInsteadOf "https://github.com/"

# -- GitHub CLI credential helper (optional) -----------------------------------
# When the host's gh CLI binary and config are bind-mounted into the container,
# this enables HTTPS authentication for private repo clones (e.g. Microsoft
# amplifier modules). Without this, only public repos can be cloned over HTTPS.
# RUN git config --global credential.helper "!gh auth git-credential" expands to the git credential config line, or empty.
RUN git config --global credential.helper "!gh auth git-credential"

# -- SSH directory for known_hosts bind-mount ----------------------------------
RUN mkdir -p /Users/chrispark/.ssh && chmod 700 /Users/chrispark/.ssh

# -- Pre-create .amplifier dir ------------------------------------------------
# For named volumes: Docker inherits ownership from the container directory at
# first mount, so pre-creating ensures correct ownership.
# For bind mounts: this image layer is shadowed — the entrypoint.sh guard
# handles cache/ creation and ownership diagnostics at runtime instead.
RUN mkdir -p /Users/chrispark/.amplifier/cache

# -- Entrypoint ----------------------------------------------------------------
COPY --chown=501:20 .dev-machine/scripts/entrypoint.sh /Users/chrispark/entrypoint.sh
RUN chmod +x /Users/chrispark/entrypoint.sh

WORKDIR /Users/chrispark/Projects/ridecast2

# -- Project dependencies installed at runtime by entrypoint.sh ----------------
# (Project directory is bind-mounted, not available at build time.)

ENTRYPOINT ["/Users/chrispark/entrypoint.sh"]
CMD ["amplifier", "tool", "invoke", "recipes", "operation=execute", \
     "recipe_path=/Users/chrispark/Projects/ridecast2/.dev-machine/recipes/dev-machine-build.yaml"]

