#!/usr/bin/env bash
# Generated by amplifier-bundle-dev-machine — do not edit directly
# =============================================================================
# Container entrypoint: seed config, install deps, then run command with retries.
#
# The retry loop makes the dev machine resilient to transient LLM provider
# errors (overloaded_error, rate limits, network blips). On failure the
# recipe is restarted after a backoff delay -- STATE.yaml ensures it picks
# up where it left off.
#
# Cloudflare handling: Before each attempt, a pre-flight check pings the
# Anthropic API. If Cloudflare returns a managed challenge (403 + "Just a
# moment..."), we wait with a long backoff instead of launching and crashing.
# Quick crashes (< 120s) also trigger CF-aware longer backoff.
# =============================================================================

set -euo pipefail

AMPLIFIER_DIR="$HOME/.amplifier"
MAX_BACKOFF=300          # 5 minutes ceiling (normal errors)
CF_BACKOFF=900           # default 900 = 15 minutes (Cloudflare challenge detected)
INITIAL_BACKOFF=30       # start at 30 seconds
SUCCESS_RESET=600        # if a run lasts > 10 min, reset backoff (it was working)
CF_CRASH_THRESHOLD=120   # if crash < 2 min, assume Cloudflare
INTER_SESSION_COOLDOWN=60  # default 60s pause between successful sessions to reduce CF triggers
CF_BACKOFF_MAX=2700      # default 2700 = 45 min ceiling for CF preflight exponential backoff
MAX_CONSECUTIVE_FAILURES=${MAX_CONSECUTIVE_FAILURES:-5}  # halt after N back-to-back structural failures
MAX_IDLE_SESSIONS=${MAX_IDLE_SESSIONS:-3}  # halt after N consecutive sessions with no meaningful code changes

# Branching mode: when set to "true", working sessions commit to feature branches
# and create PRs at session boundaries instead of committing directly to main.
# Override via environment variable, then fall back to the generation-time config value.
BRANCHING_MODE=${BRANCHING_MODE:-false}

# Heartbeat file: the entrypoint touches this before every significant sleep
# so the external watchdog can distinguish "alive, managing its own backoff"
# from "truly stuck."  Must be on the bind-mounted project dir so the host
# watchdog can stat it.
HEARTBEAT_FILE="/Users/chrispark/Projects/ridecast2/.dev-machine-heartbeat"

# Container log: mirror all entrypoint output to a host-visible file so the
# operator agent (and humans) can read it without `docker logs`.
CONTAINER_LOG="/Users/chrispark/Projects/ridecast2/dev-machine-container.log"
if [ -f "$CONTAINER_LOG" ] && [ "$(wc -l < "$CONTAINER_LOG" 2>/dev/null || echo 0)" -gt 10000 ]; then
    tail -5000 "$CONTAINER_LOG" > "${CONTAINER_LOG}.tmp" && mv "${CONTAINER_LOG}.tmp" "$CONTAINER_LOG"
fi
exec > >(tee -a "$CONTAINER_LOG") 2>&1

touch_heartbeat() {
    touch "$HEARTBEAT_FILE" 2>/dev/null || true
}

# -- Display escalation file if present (called inside halt loops) ---------------
# When a session writes .dev-machine/escalation.json it signals that ALL work
# is blocked and a human decision is needed. We surface it on every halt-loop
# wake-up so the host operator sees it in `docker logs` without digging.
show_escalation() {
    local esc_file="/Users/chrispark/Projects/ridecast2/.dev-machine/escalation.json"
    if [ -f "$esc_file" ]; then
        echo ""
        echo "[entrypoint] *** ESCALATION FILE FOUND: human input required ***"
        cat "$esc_file"
        echo ""
    fi
}

# -- Pre-flight: check if Anthropic API is reachable --------------------------
check_api() {
    # Minimal request to Anthropic API -- just enough to see if CF blocks us.
    # Uses the ANTHROPIC_API_KEY from env (loaded via env_file in compose).
    local api_key="${ANTHROPIC_API_KEY:-}"
    if [ -z "$api_key" ]; then
        echo "[preflight] No ANTHROPIC_API_KEY set, skipping check"
        return 0
    fi

    local response
    local http_code
    # Use the read-only models endpoint instead of POST /v1/messages.
    # A GET is lighter, costs nothing, and looks less bot-like to Cloudflare.
    # 200 = API reachable. 403 + HTML = Cloudflare challenge.
    http_code=$(curl -s -o /tmp/cf-check-body.txt -w '%{http_code}' \
        https://api.anthropic.com/v1/models \
        -H "x-api-key: $api_key" \
        -H "anthropic-version: 2023-06-01" \
        --connect-timeout 10 \
        --max-time 15 \
        2>/dev/null) || http_code="000"

    if [ "$http_code" = "403" ]; then
        # Check if it's actually Cloudflare (HTML body with "Just a moment")
        if grep -q "Just a moment" /tmp/cf-check-body.txt 2>/dev/null; then
            echo "[preflight] CLOUDFLARE CHALLENGE DETECTED (403 + managed challenge)"
            return 1
        fi
    fi

    if [ "$http_code" = "000" ]; then
        echo "[preflight] API unreachable (connection failed)"
        return 1
    fi

    if [ "$http_code" = "529" ] || [ "$http_code" = "503" ]; then
        echo "[preflight] API overloaded ($http_code)"
        return 1
    fi

    # 200 = success (unlikely with our minimal payload), 400 = bad request (expected),
    # 401 = bad key, 429 = rate limit -- all mean the API is reachable (not CF-blocked)
    echo "[preflight] API reachable (HTTP $http_code)"
    rm -f /tmp/cf-check-body.txt
    return 0
}

# -- Ensure ~/.amplifier/cache is writable ------------------------------------
# Bind mounts shadow the Dockerfile's pre-created image layer. On first run,
# Docker may have created the source dir as root, or cache/ may not exist yet.
# Pre-create here as the container user so Amplifier can install providers and
# bundles without "Permission denied".
if [ ! -d "$AMPLIFIER_DIR/cache" ]; then
    if ! mkdir -p "$AMPLIFIER_DIR/cache" 2>/dev/null; then
        echo "[entrypoint] FATAL: Cannot create $AMPLIFIER_DIR/cache"
        echo "[entrypoint] The bind-mount source directory may be root-owned."
        echo "[entrypoint] Fix on HOST: docker run --rm -v <bind-mount-path>:/fix alpine chown -R $(id -u):$(id -g) /fix"
        exit 1
    fi
    echo "[entrypoint] Created $AMPLIFIER_DIR/cache"
fi

# -- Seed config files (first run with named volume) --------------------------
if [ -f /config/keys.env ] && [ ! -f "$AMPLIFIER_DIR/keys.env" ]; then
    cp /config/keys.env "$AMPLIFIER_DIR/keys.env"
    chmod 600 "$AMPLIFIER_DIR/keys.env"
fi

if [ -f /config/settings.yaml ] && [ ! -f "$AMPLIFIER_DIR/settings.yaml" ]; then
    cp /config/settings.yaml "$AMPLIFIER_DIR/settings.yaml"
fi

echo "Amplifier config ready at $AMPLIFIER_DIR"

# Source the keys.env so ANTHROPIC_API_KEY is available for pre-flight
if [ -f "$AMPLIFIER_DIR/keys.env" ]; then
    set -a
    source "$AMPLIFIER_DIR/keys.env" 2>/dev/null || true
    set +a
fi

# -- Install project dependencies if needed ------------------------------------
# Install project dependencies (npm ci for reproducible installs)
if [ -f "/Users/chrispark/Projects/ridecast2/package-lock.json" ]; then
    echo "[entrypoint] Installing npm dependencies (npm ci)..."
    cd "/Users/chrispark/Projects/ridecast2" && npm ci --prefer-offline 2>&1 | tail -10
    echo "[entrypoint] npm dependencies ready."
fi

# -- Auto-install missing Amplifier module dependencies -------------------------
# Some Amplifier modules (tool-mcp, tool-web) require Python packages that are
# not installed by default. Detect and install them into the Amplifier tool venv
# so modules load cleanly. This is idempotent — uv skips already-installed packages.
if command -v amplifier >/dev/null 2>&1; then
    echo "[entrypoint] Checking for missing Amplifier module dependencies..."
    # Amplifier lives in a uv tool venv — find its Python and install there
    AMP_PYTHON="$(dirname "$(command -v amplifier)")/python3"
    if [ ! -x "$AMP_PYTHON" ]; then
        AMP_PYTHON="$(dirname "$(readlink -f "$(command -v amplifier)")")/python3"
    fi
    MISSING_DEPS=""
    $AMP_PYTHON -c "import mcp" 2>/dev/null || MISSING_DEPS="$MISSING_DEPS mcp"
    $AMP_PYTHON -c "import aiohttp" 2>/dev/null || MISSING_DEPS="$MISSING_DEPS aiohttp"
    if [ -n "$MISSING_DEPS" ]; then
        echo "[entrypoint] Installing missing module deps:$MISSING_DEPS"
        # Install into the amplifier tool venv using uv pip
        AMP_VENV="$(dirname "$(dirname "$(command -v amplifier)")")"
        uv pip install --python "$AMP_PYTHON" $MISSING_DEPS 2>&1 | tail -5
    else
        echo "[entrypoint] All module dependencies present."
    fi
fi

# -- Cancel stale recipe sessions ----------------------------------------------
# Recipe sessions persist their state (including the recipe YAML contents) at
# creation time. When a container is rebuilt with updated recipe files, any
# existing sessions will RESUME with the OLD recipe baked in — changes to
# .dev-machine/*.yaml on disk are invisible to resumed sessions.
#
# By cancelling all active sessions at container startup, we guarantee the
# retry loop below always starts fresh with the current recipe files.
# Within a single container lifecycle this is harmless: each loop iteration
# invokes "$@" which creates a new session anyway.
echo "[entrypoint] Cancelling stale recipe sessions (if any)..."
stale_sessions=$(amplifier tool invoke recipes operation=list 2>/dev/null | \
    python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    sessions = data if isinstance(data, list) else data.get('sessions', [])
    for s in sessions:
        sid = s.get('session_id', s.get('id', ''))
        status = s.get('status', '')
        if sid and status not in ('completed', 'failed', 'cancelled', 'denied'):
            print(sid)
except:
    pass
" 2>/dev/null) || true

if [ -n "$stale_sessions" ]; then
    count=0
    while IFS= read -r sid; do
        amplifier tool invoke recipes operation=cancel session_id="$sid" immediate=true 2>/dev/null || true
        count=$((count + 1))
    done <<< "$stale_sessions"
    echo "[entrypoint] Cancelled $count stale recipe session(s)."
else
    echo "[entrypoint] No stale sessions found."
fi

# -- Run command with retry loop ----------------------------------------------
backoff=$INITIAL_BACKOFF
attempt=0
consecutive_structural_failures=0
# Persist idle counter to disk so it survives container restarts (WSL crashes etc.)
IDLE_COUNT_FILE="/Users/chrispark/Projects/ridecast2/.dev-machine/.dev-machine-idle-count"
if [ -f "$IDLE_COUNT_FILE" ]; then
    consecutive_idle_sessions=$(cat "$IDLE_COUNT_FILE" 2>/dev/null || echo 0)
    # Validate it's a number
    if ! [ "$consecutive_idle_sessions" -eq "$consecutive_idle_sessions" ] 2>/dev/null; then
        consecutive_idle_sessions=0
    fi
    echo "[entrypoint] Restored idle counter from disk: $consecutive_idle_sessions / $MAX_IDLE_SESSIONS"
else
    consecutive_idle_sessions=0
fi

save_idle_count() {
    echo "$consecutive_idle_sessions" > "$IDLE_COUNT_FILE" 2>/dev/null || true
}

while true; do
    attempt=$((attempt + 1))

    echo ""
    echo "=========================================="
    echo "  Dev Machine -- attempt $attempt"
    echo "  $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
    echo "=========================================="
    echo ""

    # Pre-flight API check -- wait for Cloudflare to clear before launching.
    # Uses exponential backoff (15 min → 30 min → 45 min cap) so we make
    # fewer requests during long CF blocks, giving CF more time to forget us.
    touch_heartbeat
    cf_wait_count=0
    cf_current_backoff=$CF_BACKOFF
    while ! check_api; do
        cf_wait_count=$((cf_wait_count + 1))
        touch_heartbeat
        echo "[entrypoint] API not reachable. Waiting ${cf_current_backoff}s before retry... (preflight check $cf_wait_count)"
        sleep $cf_current_backoff
        # Exponential backoff: fewer requests = faster CF recovery
        cf_current_backoff=$((cf_current_backoff * 2))
        if [ $cf_current_backoff -gt $CF_BACKOFF_MAX ]; then
            cf_current_backoff=$CF_BACKOFF_MAX
        fi
    done

    if [ $cf_wait_count -gt 0 ]; then
        echo "[entrypoint] API reachable after $cf_wait_count preflight retries."
    fi

    start_time=$(date +%s)

    # Snapshot git HEAD before recipe runs -- used for idle-cycle detection
    pre_session_head=$(git -C "/Users/chrispark/Projects/ridecast2" rev-parse HEAD 2>/dev/null || echo "")

    # -- PRE-CHECK: skip expensive recipe if no work available -----------------
    # Reads STATE.yaml in ~0.1s with Python. If there are no ready/in-progress
    # features and no actionable next_action, skip the entire LLM session + test
    # suite to stop burning money on idle cycles.
    WORK_AVAILABLE=$(python3 << 'PRECHECK'
import yaml, sys
try:
    with open("/Users/chrispark/Projects/ridecast2/.dev-machine/STATE.yaml") as f:
        state = yaml.safe_load(f)
    blockers = state.get("blockers", [])
    if blockers:
        print("blocked")
        sys.exit(0)
    completed = set(state.get("completed_features", []))
    features = state.get("features", {})
    has_work = False
    for fid, fd in features.items():
        s = fd.get("status", "")
        if s == "in-progress":
            has_work = True
            break
        if s == "ready":
            deps = fd.get("depends_on", [])
            if all(d in completed or features.get(d, {}).get("status") in ("completed", "done") for d in deps):
                has_work = True
                break
    if has_work:
        print("work")
    else:
        print("idle")
except Exception as e:
    print("work")  # on error, let the recipe run
PRECHECK
    )
    if [ "$WORK_AVAILABLE" = "idle" ]; then
        echo "[entrypoint] PRE-CHECK: No actionable work in STATE.yaml — skipping expensive recipe."
        echo "[entrypoint] (No ready/in-progress features, no blockers to fix.)"
        exit_code=0
        end_time=$(date +%s)
        duration=5
        RECIPE_LOG="/tmp/recipe-output-$attempt.log"
        echo "[pre-check skip]" > "$RECIPE_LOG"
    elif [ "$WORK_AVAILABLE" = "blocked" ]; then
        echo "[entrypoint] PRE-CHECK: Project is BLOCKED — skipping recipe. Fix blockers in STATE.yaml."
        exit_code=0
        end_time=$(date +%s)
        duration=5
        RECIPE_LOG="/tmp/recipe-output-$attempt.log"
        echo "[pre-check skip - blocked]" > "$RECIPE_LOG"
    else
        echo "[entrypoint] PRE-CHECK: Work available — launching recipe."
    fi

    if [ "$WORK_AVAILABLE" = "work" ]; then
    # Run the command; capture exit code and tee output for CF detection
    RECIPE_LOG="/tmp/recipe-output-$attempt.log"
    set +e
    "$@" 2>&1 | tee "$RECIPE_LOG"
    exit_code=${PIPESTATUS[0]}
    set -e
    fi  # end if WORK_AVAILABLE == "work"

    end_time=$(date +%s)
    duration=$((end_time - start_time))

    # Check recipe output for mid-session Cloudflare challenge signature
    cf_mid_session=false
    if grep -q "Just a moment" "$RECIPE_LOG" 2>/dev/null; then
        cf_mid_session=true
        echo ""
        echo "[entrypoint] CLOUDFLARE CHALLENGE detected in recipe output (mid-session)."
    fi

    # Check if `amplifier tool invoke` reported an internal recipe failure.
    # The CLI exits 0 even when a recipe step fails with on_error=fail,
    # so we must inspect stdout.  Treat as a real error to avoid silent
    # 60-second loops that waste an entire night (the 514-attempt incident).
    recipe_internal_fail=false
    if [ $exit_code -eq 0 ] && grep -q "Recipe execution failed" "$RECIPE_LOG" 2>/dev/null; then
        recipe_internal_fail=true
        # Extract the failing step name for the log
        failing_step=$(grep -oP "Step '\K[^']+" "$RECIPE_LOG" 2>/dev/null | head -1)
        echo ""
        echo "[entrypoint] WARNING: recipe exited 0 but reported internal failure (step: ${failing_step:-unknown})."
        echo "[entrypoint] Treating as error to prevent silent loop."
        exit_code=1
    fi

    # Save tail before deleting -- used by post-mortem if we hit the failure cap
    last_log_lines=$(tail -20 "$RECIPE_LOG" 2>/dev/null || echo "(no log available)")
    rm -f "$RECIPE_LOG"

    # -- Test environment broken: skip retry loop entirely -------------------------
    # The test-env-preflight step writes this sentinel when the test RUNNER is
    # structurally broken (not just failing tests). Retrying will never fix a broken
    # test runner -- go straight to postmortem+halt, same as idle/structural caps.
    # Clear path: fix the runner, delete .dev-machine-test-env-broken, modify
    # STATE.yaml (or restart container) to resume.
    if [ -f "/Users/chrispark/Projects/ridecast2/.dev-machine-test-env-broken" ]; then
        echo ""
        echo "[entrypoint] TEST-ENV-BROKEN sentinel detected."
        echo "[entrypoint] The test runner is structurally broken -- retrying will not help."
        echo "[entrypoint] Skipping retry loop. Writing postmortem and halting."

        POSTMORTEM_FILE="/Users/chrispark/Projects/ridecast2/.dev-machine-postmortem"
        if [ ! -f "$POSTMORTEM_FILE" ]; then
            # Fallback postmortem in case the recipe step didn't write one
            {
                echo "=== Dev Machine Post-Mortem: Test Environment Broken ==="
                echo "Date:   $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
                echo "Reason: .dev-machine-test-env-broken sentinel file found after attempt $attempt"
                echo ""
                echo "The test-env-preflight step detected a broken test runner."
                echo "Retrying will not fix a structural test environment failure."
                echo ""
                echo "To resume: fix the test runner error, then:"
                echo "  1. Delete /Users/chrispark/Projects/ridecast2/.dev-machine-test-env-broken"
                echo "  2. Modify STATE.yaml (or restart the container)"
                echo "  (The postmortem file is auto-deleted on resume.)"
                echo ""
                echo "=== Last log lines ==="
                echo "$last_log_lines"
            } > "$POSTMORTEM_FILE"
        fi
        echo "[entrypoint] Post-mortem at $POSTMORTEM_FILE"

        STATE_FILE="/Users/chrispark/Projects/ridecast2/.dev-machine/STATE.yaml"
        state_mtime=$(stat -c '%Y' "$STATE_FILE" 2>/dev/null || echo "0")
        touch_heartbeat

        echo "[entrypoint] Entering halt loop. Fix test runner, remove .dev-machine-test-env-broken, then modify STATE.yaml to resume."
        while true; do
            sleep 300
            touch_heartbeat
            new_mtime=$(stat -c '%Y' "$STATE_FILE" 2>/dev/null || echo "0")
            # Resume if sentinel was deleted OR STATE.yaml was manually modified
            if [ ! -f "/Users/chrispark/Projects/ridecast2/.dev-machine-test-env-broken" ] || [ "$new_mtime" != "$state_mtime" ]; then
                echo ""
                echo "[entrypoint] Halt cleared (sentinel removed or STATE.yaml modified) -- resuming."
                echo ""
                rm -f "$POSTMORTEM_FILE"
                break
            fi
            show_escalation
            echo "[entrypoint] Still halted -- test-env-broken ($(date -u '+%H:%M:%S UTC')). Remove .dev-machine-test-env-broken to resume."
        done
        continue
    fi

    # On success: loop back for next session (don't exit -- container stays alive)
    if [ $exit_code -eq 0 ]; then
        echo ""
        echo "[entrypoint] Recipe completed cleanly (code 0) after ${duration}s."
        backoff=$INITIAL_BACKOFF
        consecutive_structural_failures=0

        # -- Idle-cycle detection: did the session produce meaningful code changes? --
        post_session_head=$(git -C "/Users/chrispark/Projects/ridecast2" rev-parse HEAD 2>/dev/null || echo "")
        if [ -n "$pre_session_head" ] && [ -n "$post_session_head" ]; then
            # Count lines of diff excluding bookkeeping files
            meaningful_diff=$(git -C "/Users/chrispark/Projects/ridecast2" diff "$pre_session_head" "$post_session_head" \
                -- . \
                ':(exclude)STATE.yaml' \
                ':(exclude)CONTEXT-TRANSFER.md' \
                ':(exclude)SESSION-ARCHIVE.md' \
                ':(exclude)FEATURE-ARCHIVE.yaml' \
                ':(exclude).dev-machine-heartbeat' \
                ':(exclude).dev-machine-postmortem' \
                ':(exclude).dev-machine-idle-count' \
                ':(exclude)dev-machine-container.log' \
                2>/dev/null | wc -l)

            if [ "$meaningful_diff" -eq 0 ]; then
                consecutive_idle_sessions=$((consecutive_idle_sessions + 1))
                save_idle_count
                echo "[entrypoint] IDLE SESSION: no meaningful code changes (${consecutive_idle_sessions}/${MAX_IDLE_SESSIONS})"

                if [ $consecutive_idle_sessions -ge $MAX_IDLE_SESSIONS ]; then
                    echo ""
                    echo "[entrypoint] HALTING: $MAX_IDLE_SESSIONS consecutive sessions produced no code changes."
                    echo "[entrypoint] The machine appears blocked or stuck in a loop."
                    echo ""

                    # Write postmortem (same pattern as structural failure halt)
                    POSTMORTEM_FILE="/Users/chrispark/Projects/ridecast2/.dev-machine-postmortem"
                    {
                        echo "=== Dev Machine Post-Mortem ==="
                        echo "Date:                        $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
                        echo "Reason:                      idle-cycle cap ($MAX_IDLE_SESSIONS consecutive sessions with no code changes)"
                        echo "Consecutive idle sessions:   $consecutive_idle_sessions / $MAX_IDLE_SESSIONS"
                        echo "Last session duration:       ${duration}s"
                        echo "Total attempts:              $attempt"
                        echo ""
                        echo "The machine completed $MAX_IDLE_SESSIONS sessions successfully but none"
                        echo "produced meaningful code changes (only state/bookkeeping file updates)."
                        echo "This typically means the machine is blocked and confirming it each cycle."
                        echo ""
                        echo "To resume: fix the blocking issue in STATE.yaml, then modify STATE.yaml"
                        echo "(or restart the container)."
                        echo ""
                        echo "=== Last log lines ==="
                        echo "$last_log_lines"
                    } > "$POSTMORTEM_FILE"
                    echo "[entrypoint] Post-mortem written to $POSTMORTEM_FILE"

                    # Enter halt loop (same as structural failure halt)
                    STATE_FILE="/Users/chrispark/Projects/ridecast2/.dev-machine/STATE.yaml"
                    state_mtime=$(stat -c '%Y' "$STATE_FILE" 2>/dev/null || echo "0")
                    touch_heartbeat

                    echo "[entrypoint] Entering halt loop. Modify STATE.yaml or restart the container to resume."
                    while true; do
                        sleep 300
                        touch_heartbeat
                        new_mtime=$(stat -c '%Y' "$STATE_FILE" 2>/dev/null || echo "0")
                        if [ "$new_mtime" != "$state_mtime" ]; then
                            echo ""
                            echo "[entrypoint] STATE.yaml modified -- clearing halt, resuming."
                            echo ""
                            consecutive_idle_sessions=0
                            save_idle_count
                            rm -f "$POSTMORTEM_FILE"
                            break
                        fi
                        show_escalation
                        echo "[entrypoint] Still halted -- idle cap ($(date -u '+%H:%M:%S UTC')). Modify STATE.yaml to resume."
                    done
                fi
            else
                # Real work happened -- reset idle counter
                consecutive_idle_sessions=0
                save_idle_count
                echo "[entrypoint] Session produced meaningful changes (+${meaningful_diff} diff lines)."
            fi
        fi

        echo "[entrypoint] Cooling down ${INTER_SESSION_COOLDOWN}s before next session..."
        echo ""
        touch_heartbeat
        sleep $INTER_SESSION_COOLDOWN
        continue
    fi

    # If the run lasted long enough, it was making progress -- reset backoff
    if [ $duration -ge $SUCCESS_RESET ]; then
        backoff=$INITIAL_BACKOFF
        echo "[entrypoint] Run lasted ${duration}s (progress detected). Resetting backoff."
    fi

    # CF detected mid-session OR quick crash -- use extended backoff
    if [ "$cf_mid_session" = true ] || [ $duration -lt $CF_CRASH_THRESHOLD ]; then
        echo ""
        if [ "$cf_mid_session" = true ]; then
            echo "[entrypoint] Mid-session Cloudflare challenge confirmed."
        else
            echo "[entrypoint] QUICK CRASH (${duration}s < ${CF_CRASH_THRESHOLD}s threshold)."
            echo "[entrypoint] Likely Cloudflare challenge or API issue."
        fi
        echo "[entrypoint] Using extended backoff: ${CF_BACKOFF}s (attempt $attempt)"
        echo ""
        consecutive_structural_failures=0
        touch_heartbeat
        sleep $CF_BACKOFF
        # Don't increase backoff further -- CF_BACKOFF is already long
        continue
    fi

    echo ""
    echo "[entrypoint] Recipe exited with code $exit_code after ${duration}s."
    echo "[entrypoint] Retrying in ${backoff}s... (attempt $attempt)"
    echo ""

    touch_heartbeat
    sleep $backoff

    # Exponential backoff with cap
    backoff=$((backoff * 2))
    if [ $backoff -gt $MAX_BACKOFF ]; then
        backoff=$MAX_BACKOFF
    fi

    # -- Classify and track consecutive structural failures ----------------------
    # Structural = long-running failure (>= 60s) or explicit recipe_internal_fail.
    # Quick crashes that slipped past the CF filter are still treated as transient.
    if [ $duration -lt 60 ] && [ "$recipe_internal_fail" != "true" ]; then
        echo "[entrypoint] Quick crash (${duration}s < 60s) -- transient, structural counter unchanged (${consecutive_structural_failures}/${MAX_CONSECUTIVE_FAILURES})."
    else
        consecutive_structural_failures=$((consecutive_structural_failures + 1))
        echo "[entrypoint] Structural failure #${consecutive_structural_failures}/${MAX_CONSECUTIVE_FAILURES} (exit ${exit_code}, ${duration}s)."

        if [ $consecutive_structural_failures -ge $MAX_CONSECUTIVE_FAILURES ]; then
            echo ""
            echo "[entrypoint] CRITICAL: MAX_CONSECUTIVE_FAILURES ($MAX_CONSECUTIVE_FAILURES) reached. Halting retry loop."
            echo ""

            # -- Diagnose probable cause from last log lines ---------------------------
            probable_cause="Unknown"
            recovery_action="Investigate the last log lines below for the root cause."
            if echo "$last_log_lines" | grep -qi "internal server error\|api_error\|overloaded_error\|529\|503"; then
                probable_cause="LLM provider outage or overload"
                recovery_action="Likely transient. Wait for the provider to recover, then resume with:  touch STATE.yaml"
            elif echo "$last_log_lines" | grep -qi "Just a moment\|cloudflare\|cf-challenge"; then
                probable_cause="Cloudflare challenge (bot detection)"
                recovery_action="Wait 30-60 minutes for CF to clear, then resume with:  touch STATE.yaml"
            elif echo "$last_log_lines" | grep -qi "rate.limit\|429\|too many requests"; then
                probable_cause="API rate limiting"
                recovery_action="Wait 15-30 minutes, then resume with:  touch STATE.yaml"
            elif echo "$last_log_lines" | grep -qi "ModuleValidationError\|ImportError\|ModuleNotFoundError"; then
                probable_cause="Missing Python module or broken Amplifier install"
                recovery_action="Check container has required packages. May need:  docker compose -f docker-compose.dev-machine.yaml up -d --build"
            elif echo "$last_log_lines" | grep -qi "Recipe execution failed"; then
                probable_cause="Recipe step failure (check which step failed in logs)"
                recovery_action="Read the full postmortem below. If recipe files were changed, restart container to pick up changes."
            elif echo "$last_log_lines" | grep -qi "permission denied\|EACCES"; then
                probable_cause="File permission error (root-owned files?)"
                recovery_action="Fix permissions:  sudo chown -R \$(id -u):\$(id -g) /Users/chrispark/Projects/ridecast2"
            fi

            # Write a post-mortem file for human review
            POSTMORTEM_FILE="/Users/chrispark/Projects/ridecast2/.dev-machine-postmortem"
            {
                echo "=== Dev Machine Post-Mortem ==="
                echo ""
                echo "Date:              $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
                echo "Halt reason:       $MAX_CONSECUTIVE_FAILURES consecutive structural failures"
                echo "Probable cause:    $probable_cause"
                echo "Last exit code:    $exit_code"
                echo "Last duration:     ${duration}s"
                echo "Total attempts:    $attempt"
                echo ""
                echo "=== Recovery ==="
                echo ""
                echo "  $recovery_action"
                echo ""
                echo "  Quick resume (transient issues like LLM outages):"
                echo "    touch /Users/chrispark/Projects/ridecast2/.dev-machine/STATE.yaml"
                echo ""
                echo "  Full restart (after fixing config/recipe files):"
                echo "    docker compose -f docker-compose.dev-machine.yaml restart"
                echo ""
                echo "  Rebuild (after Dockerfile or dependency changes):"
                echo "    docker compose -f docker-compose.dev-machine.yaml up -d --build"
                echo ""
                echo "=== Last 20 Log Lines ==="
                echo ""
                echo "$last_log_lines"
            } > "$POSTMORTEM_FILE"
            echo "[entrypoint] Post-mortem written to $POSTMORTEM_FILE"

            # Record STATE.yaml mtime so a human can resume by touching/modifying it
            STATE_FILE="/Users/chrispark/Projects/ridecast2/.dev-machine/STATE.yaml"
            state_mtime=$(stat -c '%Y' "$STATE_FILE" 2>/dev/null || echo "0")

            touch_heartbeat

            echo ""
            echo "=========================================="
            echo "  MACHINE HALTED"
            echo "=========================================="
            echo ""
            echo "  Probable cause:  $probable_cause"
            echo "  Recovery:        $recovery_action"
            echo ""
            echo "  Quick resume:    touch /Users/chrispark/Projects/ridecast2/.dev-machine/STATE.yaml"
            echo "  Full restart:    docker compose -f docker-compose.dev-machine.yaml restart"
            echo "  Postmortem:      cat /Users/chrispark/Projects/ridecast2/.dev-machine-postmortem"
            echo ""
            echo "  The machine checks STATE.yaml every 5 minutes."
            echo "  Touch it to resume, or restart the container."
            echo ""
            echo "=========================================="

            while true; do
                sleep 300
                touch_heartbeat
                new_mtime=$(stat -c '%Y' "$STATE_FILE" 2>/dev/null || echo "0")
                if [ "$new_mtime" != "$state_mtime" ]; then
                    echo ""
                    echo "[entrypoint] STATE.yaml modified -- clearing halt, resuming."
                    echo ""
                    rm -f "$POSTMORTEM_FILE"
                    consecutive_structural_failures=0
                    break
                fi
                show_escalation
                echo "[entrypoint] Halted: $probable_cause ($(date -u '+%H:%M:%S UTC')). touch STATE.yaml to resume."
            done
        fi
    fi
done
