-- This migration was folded into 20260325164654_add_feedback_telemetry
-- because it ran BEFORE the table was created, causing CI failures.
-- Kept as empty migration to preserve migration history integrity.
